//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDbFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportEmployee
    {
        public int EmpId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte Active { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public int OrgId { get; set; }
    
        public virtual Orgnization Orgnization { get; set; }
    }
}
